### ISSUE TITLE
errors when building for node 13

### ISSUE THREAD

**Issue by siric** [ClusterWS/cWS#29]
Build errors out on MacOS Mojave and Ubuntu 18.04 with `node 13.2.0` and `node-gyp 6.0.1`: `node-gyp rebuild`

```
CXX(target) Release/obj.target/cws/src/Addon.o
In file included from ../src/Addon.cpp:3:
../src/Addon.h:61:11: warning: 'MakeCallback' is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
    node::MakeCallback(isolate, isolate->GetCurrentContext()->Global(),
          ^
/Users/User/Library/Caches/node-gyp/13.2.0/include/node/node.h:179:1: note: 'MakeCallback' has been explicitly marked
      deprecated here
NODE_DEPRECATED("Use MakeCallback(..., async_context)",
^
/Users/User/Library/Caches/node-gyp/13.2.0/include/node/node.h:99:20: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                   ^
In file included from ../src/Addon.cpp:3:
../src/Addon.h:151:58: error: no member named 'kNormalString' in 'v8::String'
                                                 String::kNormalString, length);
                                                 ~~~~~~~~^
../src/Addon.h:222:11: warning: 'MakeCallback' is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
    node::MakeCallback(sc->isolate, sc->isolate->GetCurrentContext()->Global(),
          ^
/Users/User/Library/Caches/node-gyp/13.2.0/include/node/node.h:179:1: note: 'MakeCallback' has been explicitly marked
      deprecated here
NODE_DEPRECATED("Use MakeCallback(..., async_context)",
^
/Users/User/Library/Caches/node-gyp/13.2.0/include/node/node.h:99:20: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                   ^
In file included from ../src/Addon.cpp:3:
../src/Addon.h:445:11: warning: 'MakeCallback' is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
    node::MakeCallback(isolate, isolate->GetCurrentContext()->Global(),
          ^
/Users/User/Library/Caches/node-gyp/13.2.0/include/node/node.h:179:1: note: 'MakeCallback' has been explicitly marked
      deprecated here
NODE_DEPRECATED("Use MakeCallback(..., async_context)",
^
/Users/User/Library/Caches/node-gyp/13.2.0/include/node/node.h:99:20: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                   ^
In file included from ../src/Addon.cpp:3:
../src/Addon.h:526:5: warning: ignoring return value of function declared with 'warn_unused_result' attribute [-Wunused-result]
    cb->Call(context, Null(isolate), 1, argv);
    ^~~~~~~~ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/Addon.h:553:7: error: no viable conversion from 'MaybeLocal<v8::String>' to 'Local<v8::String>'
      String::NewFromUtf8(isolate, "Error: One object expected")));
      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/User/Library/Caches/node-gyp/13.2.0/include/node/v8.h:189:7: note: candidate constructor
      (the implicit copy constructor) not viable: no known conversion from 'MaybeLocal<v8::String>' to
      'const v8::Local<v8::String> &' for 1st argument
class Local {
      ^
/Users/User/Library/Caches/node-gyp/13.2.0/include/node/v8.h:189:7: note: candidate constructor
      (the implicit move constructor) not viable: no known conversion from 'MaybeLocal<v8::String>' to 'v8::Local<v8::String> &&'
      for 1st argument
/Users/User/Library/Caches/node-gyp/13.2.0/include/node/v8.h:193:13: note: candidate template ignored: could not match
      'Local' against 'MaybeLocal'
  V8_INLINE Local(Local<S> that)
            ^
/Users/User/Library/Caches/node-gyp/13.2.0/include/node/v8.h:6995:47: note: passing argument to parameter 'message' here
  static Local<Value> TypeError(Local<String> message);
                                              ^
In file included from ../src/Addon.cpp:3:
../src/Addon.h:612:13: error: no matching member function for call to 'Set'
    object->Set(String::NewFromUtf8(isolate, "group"), group);
    ~~~~~~~~^~~
/Users/User/Library/Caches/node-gyp/13.2.0/include/node/v8.h:3547:37: note: candidate function not viable: requires 3
      arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                    ^
/Users/User/Library/Caches/node-gyp/13.2.0/include/node/v8.h:3550:37: note: candidate function not viable: requires 3
      arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
                                    ^
../src/Addon.cpp:8:12: error: no matching member function for call to 'Set'
  exports->Set(String::NewFromUtf8(isolate, "server"),
  ~~~~~~~~~^~~
/Users/User/Library/Caches/node-gyp/13.2.0/include/node/v8.h:3547:37: note: candidate function not viable: requires 3
      arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                    ^
/Users/User/Library/Caches/node-gyp/13.2.0/include/node/v8.h:3550:37: note: candidate function not viable: requires 3
      arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
                                    ^
../src/Addon.cpp:10:12: error: no matching member function for call to 'Set'
  exports->Set(String::NewFromUtf8(isolate, "client"),
  ~~~~~~~~~^~~
/Users/User/Library/Caches/node-gyp/13.2.0/include/node/v8.h:3547:37: note: candidate function not viable: requires 3
      arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                    ^
/Users/User/Library/Caches/node-gyp/13.2.0/include/node/v8.h:3550:37: note: candidate function not viable: requires 3
      arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
                                    ^
In file included from ../src/Addon.cpp:3:
../src/Addon.h:334:15: warning: 'MakeCallback' is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
        node::MakeCallback(isolate, isolate->GetCurrentContext()->Global(),
              ^
../src/Addon.h:591:44: note: in instantiation of function template specialization 'onConnection<true>' requested here
    NODE_SET_METHOD(group, "onConnection", onConnection<isServer>);
                                           ^
../src/Addon.cpp:9:16: note: in instantiation of member function 'Namespace<true>::Namespace' requested here
               Namespace<cWS::SERVER>(isolate).object);
               ^
/Users/User/Library/Caches/node-gyp/13.2.0/include/node/node.h:179:1: note: 'MakeCallback' has been explicitly marked
      deprecated here
NODE_DEPRECATED("Use MakeCallback(..., async_context)",
^
/Users/User/Library/Caches/node-gyp/13.2.0/include/node/node.h:99:20: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                   ^
In file included from ../src/Addon.cpp:3:
../src/Addon.h:360:7: warning: ignoring return value of function declared with 'warn_unused_result' attribute [-Wunused-result]
      Local<Function>::New(isolate, *messageCallback)
      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/Addon.h:592:41: note: in instantiation of function template specialization 'onMessage<true>' requested here
    NODE_SET_METHOD(group, "onMessage", onMessage<isServer>);
                                        ^
../src/Addon.cpp:9:16: note: in instantiation of member function 'Namespace<true>::Namespace' requested here
               Namespace<cWS::SERVER>(isolate).object);
               ^
In file included from ../src/Addon.cpp:3:
../src/Addon.h:426:11: warning: 'MakeCallback' is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
    node::MakeCallback(isolate, isolate->GetCurrentContext()->Global(),
          ^
../src/Addon.h:593:47: note: in instantiation of function template specialization 'onDisconnection<true>' requested here
    NODE_SET_METHOD(group, "onDisconnection", onDisconnection<isServer>);
                                              ^
../src/Addon.cpp:9:16: note: in instantiation of member function 'Namespace<true>::Namespace' requested here
               Namespace<cWS::SERVER>(isolate).object);
               ^
/Users/User/Library/Caches/node-gyp/13.2.0/include/node/node.h:179:1: note: 'MakeCallback' has been explicitly marked
      deprecated here
NODE_DEPRECATED("Use MakeCallback(..., async_context)",
^
/Users/User/Library/Caches/node-gyp/13.2.0/include/node/node.h:99:20: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                   ^
In file included from ../src/Addon.cpp:3:
../src/Addon.h:381:11: warning: 'MakeCallback' is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
    node::MakeCallback(isolate, isolate->GetCurrentContext()->Global(),
          ^
../src/Addon.h:604:38: note: in instantiation of function template specialization 'onPing<true>' requested here
    NODE_SET_METHOD(group, "onPing", onPing<isServer>);
                                     ^
../src/Addon.cpp:9:16: note: in instantiation of member function 'Namespace<true>::Namespace' requested here
               Namespace<cWS::SERVER>(isolate).object);
               ^
/Users/User/Library/Caches/node-gyp/13.2.0/include/node/node.h:179:1: note: 'MakeCallback' has been explicitly marked
      deprecated here
NODE_DEPRECATED("Use MakeCallback(..., async_context)",
^
/Users/User/Library/Caches/node-gyp/13.2.0/include/node/node.h:99:20: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                   ^
In file included from ../src/Addon.cpp:3:
../src/Addon.h:401:11: warning: 'MakeCallback' is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
    node::MakeCallback(isolate, isolate->GetCurrentContext()->Global(),
          ^
../src/Addon.h:605:38: note: in instantiation of function template specialization 'onPong<true>' requested here
    NODE_SET_METHOD(group, "onPong", onPong<isServer>);
                                     ^
../src/Addon.cpp:9:16: note: in instantiation of member function 'Namespace<true>::Namespace' requested here
               Namespace<cWS::SERVER>(isolate).object);
               ^
/Users/User/Library/Caches/node-gyp/13.2.0/include/node/node.h:179:1: note: 'MakeCallback' has been explicitly marked
      deprecated here
NODE_DEPRECATED("Use MakeCallback(..., async_context)",
^
/Users/User/Library/Caches/node-gyp/13.2.0/include/node/node.h:99:20: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                   ^
In file included from ../src/Addon.cpp:3:
../src/Addon.h:334:15: warning: 'MakeCallback' is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
        node::MakeCallback(isolate, isolate->GetCurrentContext()->Global(),
              ^
../src/Addon.h:591:44: note: in instantiation of function template specialization 'onConnection<false>' requested here
    NODE_SET_METHOD(group, "onConnection", onConnection<isServer>);
                                           ^
../src/Addon.cpp:11:16: note: in instantiation of member function 'Namespace<false>::Namespace' requested here
               Namespace<cWS::CLIENT>(isolate).object);
               ^
/Users/User/Library/Caches/node-gyp/13.2.0/include/node/node.h:179:1: note: 'MakeCallback' has been explicitly marked
      deprecated here
NODE_DEPRECATED("Use MakeCallback(..., async_context)",
^
/Users/User/Library/Caches/node-gyp/13.2.0/include/node/node.h:99:20: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                   ^
In file included from ../src/Addon.cpp:3:
../src/Addon.h:360:7: warning: ignoring return value of function declared with 'warn_unused_result' attribute [-Wunused-result]
      Local<Function>::New(isolate, *messageCallback)
      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/Addon.h:592:41: note: in instantiation of function template specialization 'onMessage<false>' requested here
    NODE_SET_METHOD(group, "onMessage", onMessage<isServer>);
                                        ^
../src/Addon.cpp:11:16: note: in instantiation of member function 'Namespace<false>::Namespace' requested here
               Namespace<cWS::CLIENT>(isolate).object);
               ^
In file included from ../src/Addon.cpp:3:
../src/Addon.h:426:11: warning: 'MakeCallback' is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
    node::MakeCallback(isolate, isolate->GetCurrentContext()->Global(),
          ^
../src/Addon.h:593:47: note: in instantiation of function template specialization 'onDisconnection<false>' requested here
    NODE_SET_METHOD(group, "onDisconnection", onDisconnection<isServer>);
                                              ^
../src/Addon.cpp:11:16: note: in instantiation of member function 'Namespace<false>::Namespace' requested here
               Namespace<cWS::CLIENT>(isolate).object);
               ^
/Users/User/Library/Caches/node-gyp/13.2.0/include/node/node.h:179:1: note: 'MakeCallback' has been explicitly marked
      deprecated here
NODE_DEPRECATED("Use MakeCallback(..., async_context)",
^
/Users/User/Library/Caches/node-gyp/13.2.0/include/node/node.h:99:20: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                   ^
In file included from ../src/Addon.cpp:3:
../src/Addon.h:381:11: warning: 'MakeCallback' is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
    node::MakeCallback(isolate, isolate->GetCurrentContext()->Global(),
          ^
../src/Addon.h:604:38: note: in instantiation of function template specialization 'onPing<false>' requested here
    NODE_SET_METHOD(group, "onPing", onPing<isServer>);
                                     ^
../src/Addon.cpp:11:16: note: in instantiation of member function 'Namespace<false>::Namespace' requested here
               Namespace<cWS::CLIENT>(isolate).object);
               ^
/Users/User/Library/Caches/node-gyp/13.2.0/include/node/node.h:179:1: note: 'MakeCallback' has been explicitly marked
      deprecated here
NODE_DEPRECATED("Use MakeCallback(..., async_context)",
^
/Users/User/Library/Caches/node-gyp/13.2.0/include/node/node.h:99:20: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                   ^
In file included from ../src/Addon.cpp:3:
../src/Addon.h:401:11: warning: 'MakeCallback' is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
    node::MakeCallback(isolate, isolate->GetCurrentContext()->Global(),
          ^
../src/Addon.h:605:38: note: in instantiation of function template specialization 'onPong<false>' requested here
    NODE_SET_METHOD(group, "onPong", onPong<isServer>);
                                     ^
../src/Addon.cpp:11:16: note: in instantiation of member function 'Namespace<false>::Namespace' requested here
               Namespace<cWS::CLIENT>(isolate).object);
               ^
/Users/User/Library/Caches/node-gyp/13.2.0/include/node/node.h:179:1: note: 'MakeCallback' has been explicitly marked
      deprecated here
NODE_DEPRECATED("Use MakeCallback(..., async_context)",
^
/Users/User/Library/Caches/node-gyp/13.2.0/include/node/node.h:99:20: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                   ^
In file included from ../src/Addon.cpp:3:
../src/Addon.h:194:10: error: no matching member function for call to 'Set'
  array->Set(0, Integer::New(args.GetIsolate(), address.port));
  ~~~~~~~^~~
../src/Addon.cpp:17:42: note: in instantiation of function template specialization 'getAddress<true>' requested here
  NODE_SET_METHOD(exports, "getAddress", getAddress<cWS::SERVER>);
                                         ^
/Users/User/Library/Caches/node-gyp/13.2.0/include/node/v8.h:3547:37: note: candidate function not viable: requires 3
      arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                    ^
/Users/User/Library/Caches/node-gyp/13.2.0/include/node/v8.h:3550:37: note: candidate function not viable: requires 3
      arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
                                    ^
In file included from ../src/Addon.cpp:3:
../src/Addon.h:195:10: error: no matching member function for call to 'Set'
  array->Set(1, String::NewFromUtf8(args.GetIsolate(), address.address));
  ~~~~~~~^~~
/Users/User/Library/Caches/node-gyp/13.2.0/include/node/v8.h:3547:37: note: candidate function not viable: requires 3
      arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                    ^
/Users/User/Library/Caches/node-gyp/13.2.0/include/node/v8.h:3550:37: note: candidate function not viable: requires 3
      arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
                                    ^
In file included from ../src/Addon.cpp:3:
../src/Addon.h:196:10: error: no matching member function for call to 'Set'
  array->Set(2, String::NewFromUtf8(args.GetIsolate(), address.family));
  ~~~~~~~^~~
/Users/User/Library/Caches/node-gyp/13.2.0/include/node/v8.h:3547:37: note: candidate function not viable: requires 3
      arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                    ^
/Users/User/Library/Caches/node-gyp/13.2.0/include/node/v8.h:3550:37: note: candidate function not viable: requires 3
      arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
                                    ^
14 warnings and 8 errors generated.
make: *** [Release/obj.target/cws/src/Addon.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:270:12)
gyp ERR! System Darwin 19.0.0
gyp ERR! command "/usr/local/Cellar/node/13.2.0/bin/node" "/usr/local/bin/node-gyp" "rebuild"
gyp ERR! node -v v13.2.0
gyp ERR! node-gyp -v v6.0.1
gyp ERR! not ok
```

**Comment by goriunov** [comment]
@siric cws has not yet been fully adjusted for node 13+.

**Comment by siric** [comment]
apologies, I was under the assumption that https://github.com/ClusterWS/cWS/commit/74ac86391bd9cb21e7613abd8de431ce7810596e added support for it.  looking forward to it being supported!

**Comment by goriunov** [comment]
@siric node 13 is supported from version 0.17.2
